export const TRAER_TODAS_LAS_PUBLICACIONES = "TRAER_TODAS_LAS_PUBLICACIONES";
export const TRAER_PUBLICACION_POR_USUARIO = "TRAER_PUBLICACION_POR_USUARIO";
export const ACTUALIZAR_COMENTARIOS_POR_PUBLICACION = "ACTUALIZAR_COMENTARIOS_POR_PUBLICACION";
export const ESTADO_CARGANDO = "PUBLICACIONES_CARGANDO";
export const ERROR_REQUEST = "PUBLICACIONES_ERROR";
// COMENTARIOS
export const ESTADO_CARGANDO_COMENTARIO = "PUBLICACIONES_CARGANDO_COMENTARIO";
export const ERROR_COMENTARIO_REQUEST = "PUBLICACIONES_COMENTARIO_ERROR";