export const TRAER_TODAS_LAS_TAREAS = "TRAER_TODAS_LAS_TAREAS";
export const ESTADO_CARGANDO = "TAREAS_CARGANDO";
export const ERROR_REQUEST = "TAREAS_ERROR";
export const CAMBIAR_USUARIO_ID = "CAMBIAR_USUARIO_ID";
export const CAMBIAR_TITULO_TAREA = "CAMBIAR_TITULO_TAREA";
export const TAREA_AGREGADA_EDITADA = "TAREA_AGREGADA_EDITADA";
export const ACTUALIZAR_TAREAS_CHECKED = "ACTUALIZAR_TAREAS_CHECKED";
export const LIMPIAR = "LIMPIAR";